name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  test-unitaire:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
    
    - name: Configuration de Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Exécution des tests
      run: pytest
